# fly.toml app configuration file generated for zencraft-be on 2023-10-17T11:27:13+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zencraft-be"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
